name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Cache pnpm store
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 5. Install dependencies
      - name: Install dependencies
        run: pnpm install

      # 6. Prune unnecessary dependencies (optional)
      - name: Prune unnecessary dependencies
        run: pnpm prune --prod

      # 7. Build the project with increased memory limit and reduced parallelism
      - name: Build project
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          VITE_API_BASE_URL: https://app.venmail.io/api/v1
          VITE_AUTH_URL: https://app.venmail.io/auth/oauth
        run: pnpm run build --max-workers=2

      # 8. Copy files to the server using SCP
      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/*"
          target: "/var/www/vensuite"
